POST http://localhost:2929/api/uploadReview
Content-Type: application/json

{
    "placeId": "81",
    "review": "Great place, atmosphere happy to find this hidden gem!!!",
    "rating": 5,
    "creator": "67isawesonme@example.com"
}
